version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/khnam/docker/nginx/nginx-conf:/etc/nginx/conf.d
      - /home/khnam/study/study1/html:/usr/share/nginx/html
